### ISSUE TITLE
Dagger not able to inject into InjectedBaseActivityTest

### ISSUE THREAD

**Issue by twelve17** [bryanstern/dagger-instrumentation-example#3]
I'm not sure yet, but I'm guessing it's likely due to a change in Dagger 2 (since this is using the snapshot version), but compilation fails on this project with this error:

`Error:android.test.ActivityInstrumentationTestCase2 has type parameters, cannot members inject the raw type.`

If, indeed, Dagger 2 prevents this type of injection, I'm having a hard time seeing how to make this example work other than perhaps putting all the concrete test activity classes in the 'debug' variant source tree.  Any ideas?  

I'm using Android Studio 1.1.0.  

Steps to reproduce this error: Clone this git module.  Import the project into Android Studio. Go to 'Build' ->  'Make Module'.

**Comment by twelve17** [comment]
Ooops, my apologies. I just saw this: https://github.com/google/dagger/issues/108

**Comment by BackPackerDz** [comment]
Hi, did you solve your problem ? beaucse I have the same issue !

**Comment by JohannHei** [comment]
I have the same error and didn't find a solution, yet--
